### ISSUE TITLE
Warnings when block drag begins

### ISSUE THREAD

**Issue by tmickel** [google/blockly-android#103]
These do not crash the app, but consistently appear as warnings when a block drag begins.

Device: Samsung Galaxy Pro Tab SM-T520
Android version: 4.4.2

> 03-09 09:52:59.905 29228-29228/com.google.blockly.demo E/View: Asked for drag thumb metrics but no view
> 03-09 09:52:59.905 29228-29228/com.google.blockly.demo E/View: Asked to draw drag shadow but no view
> 03-09 09:52:59.915 29228-29228/com.google.blockly.demo E/View: Asked for drag thumb metrics but no view

**Comment by ChrisA89** [comment]
I think this was fixed by #486
