### ISSUE TITLE
Need to support complex shadow blocks

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-android#199]
Shadow blocks are currently not supported in the following ways:

- [ ] When attached to a next
- [ ] When the shadow block has a next
- [ ] When the shadow block has inputs other than dummy inputs.

Example:

        <block type="statement_no_input">
            <next>
                <shadow type="statement_no_input"></shadow>
            </next>
        </block>

**Comment by RoboErikG** [comment]
After some internal discussion we've decided to support complex shadow blocks in the following ways on all platforms.

- Disallow top level shadow blocks.
- Allow complex shadow blocks, but only allow shadows to have other shadows as children (enforced at xml load time and while dragging).
- Bump attempts to connect a normal block to a shadow block.
- Strongly suggest developers only use simple* shadows for kid focused apps.

*A simple block is a block with only an output or a previous connection (no next or value connections).

**Comment by RoboErikG** [comment]
@NeilFraser One more detail--when connecting a block with a shadow next between two other blocks I opted to bump the remainder instead of replacing the shadow block on next.

Does that seem reasonable to you?

**Comment by RoboErikG** [comment]
After a bit more internal discussion we're having the shadow get replaced by the remainder when it splices between blocks.
