### ISSUE TITLE
Drag-to-trash should abort if a block is not deletable.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-android#305]
- [ ] Do not delete the block.
- [ ] Revert the drag action, and any side effects.

**Comment by geppy** [comment]
What's the desired behavior here?  A bounce?  Reverting the drag?

**Comment by RoboErikG** [comment]
Reverting the drag.

And this will be easier once events are in place since we'll be collecting
the right information to do the revert.

**Comment by AnmAtAnm** [comment]
Open question #370.

**Comment by AnmAtAnm** [comment]
Current behavior respects the dragged root block's deletable flag.  Respecting children is an open question in #370.
