### ISSUE TITLE
issues found when porting the block xml parser to groovy

### ISSUE THREAD

**Issue by simonckenyon** [google/blockly-android#373]
there are some variables named in. they are an Input, so in -> input would be an easy change.

**Comment by AnmAtAnm** [comment]
I'm sorry.  I'm not understanding.  Can you provide a link to the line, or an example?

**Comment by simonckenyon** [comment]
not a big issue, but "in" is a reserved word in groovy. so naming a variable "in" causes a syntax error. i changed the two occurrences to "input", seeing as how the object was of type Input.

see:

https://github.com/google/blockly-android/blob/26d9f6a3326a3cda69cfe6fc824d4fe43c85a6bc/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L101

https://github.com/google/blockly-android/blob/f847333f8df6f9bd8c8df1a9b8877a363441d5bb/blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java#L89

**Comment by RoboErikG** [comment]
Makes sense. Feel free to submit a pull request for the rename if it'll make it easier to keep in sync.

**Comment by AnmAtAnm** [comment]
You'll want to add a list of reserved words to your Groovy generator.  This is hinted in the docs [here](https://developers.google.com/blockly/guides/create-custom-blocks/generating-code#getfieldvalue).

In our own generators (on the [google/blockly](https://github.com/google/blockly) repo), we have addReservedWords(..) methods.  For example, [in the JavaScript generator](https://github.com/google/blockly/blob/f040929bd87937eeefcac87c8937d57a68466b3b/generators/javascript.js#L45).

**Comment by RoboErikG** [comment]
To be clear, Groovy is a Java based language that's almost compatible with standard Java. Simon, you're porting the Android version of Blockly to Groovy, not adding a generator, correct?

**Comment by simonckenyon** [comment]
that is correct.
i'm using blockly as a system for defining "drug regimes". as in: take this drug for 14 days, at 8am, noon and 4pm.
by using blockly i can put this functionality in the hands of end-users.
the XML that blockly emits is then parsed to generate the acutual schedule.

probably not the most conventional use. but there you go.

**Comment by AnmAtAnm** [comment]
Apologies for not reading through carefully enough the first time.

So you have effectively bypassed the JavaScript generator, effectively to create your own in the Java/Dalvik VM.  Cool!

I think this is a completely legitimate use.  Perhaps I should consider wrapping our generator framework in an interface that can be replaced by things such as yours.

Is there any reason you prefer to parse the XML, rather than build from the Java Block objects directly?

**Comment by simonckenyon** [comment]
sorry for the delay responding.
i parse the XML because that is what i store on the server side as string objects in a MySQL database. it can be a long time later that the XML is parsed and the "drug regime" generated.
and also because i use blockly (and not blockly-android) to generate the XML in the first place.

**Comment by AnmAtAnm** [comment]
thanks for the insight.
It seems you found a solution, so I'm going to close this issue.
