### ISSUE TITLE
Stop executing code

### ISSUE THREAD

**Issue by edi233** [google/blockly-android#474]
Hi,
there is any way to stop executing code? 
I want to create button, where I run my turtle and I want to stop my turtle whenever I want, even in the middle of my code. This is possible?

**Comment by AnmAtAnm** [comment]
Blockly isn't responsible for running code.  In our Turtle demo, we send the generated JavaScript to a WebView for execution.  See [`Turtle.execute()`](https://github.com/google/blockly-android/blob/master/blocklydemo/src/main/assets/turtle/turtle.js#L165).

The demo directly [`eval()`](https://github.com/google/blockly-android/blob/master/blocklydemo/src/main/assets/turtle/turtle.js#L165)s code in the web page.  While this is simple (and good for a demo), it is neither flexible nor safe. We generally recommend applications executing JavaScript to use [JS Interpreter](https://github.com/NeilFraser/JS-Interpreter).  See all of the details [in our docs](https://developers.google.com/blockly/guides/app-integration/running-javascript).

In the [JS Interpreter docs](https://neil.fraser.name/software/JS-Interpreter/docs.html), there are details on running code step by step.  You can use this and some `isPlaying` state variable to loop through the code.

If you need help, you should be able to reach out to the [Blockly mailing list](https://groups.google.com/forum/#!forum/blockly) for guidance, as JS Interpreter is very commonly used within the community.
