### ISSUE TITLE
cannot import com.google.blockly.android.AbstractBlocklyActivity

### ISSUE THREAD

**Issue by lijiansong** [google/blockly-android#521]
when I follow the [guides ](https://developers.google.com/blockly/guides/get-started/android) to config my android project, I cannot import com.google.blockly.android.AbstractBlocklyActivity, anyone meet similar situation?

**Comment by RoboErikG** [comment]
Could you confirm you've imported and added the blocklylib-core and blocklylib-vertical libraries to your app?

1. Import blocklylib-core-debug.aar and blocklylib-vertical-debug.aar using the + in project structure.
2. In the app module of the project structure add support-v4, appcompat-v7, recyclerview-v7, blocklylib-core-debug, and blocklylib-vertical-debug as dependencies.

**Comment by lijiansong** [comment]
Yes, I have already imported and added the blocklylib-core and blocklylib-vertical libraries to your app, even so it doesn't work.
Finally I managed to solve it by building the project twice, the first building will genearte blocklylib-core and blocklylib-vertical libraries, delete them, and build the project again, and then it works. How odd!

**Comment by lijiansong** [comment]
I also have a questing, why the json file must be in the assets folder, that means I cannot dynamicly generate the json files in android's assets folder?

**Comment by AnmAtAnm** [comment]
Glad you got it working.

We expect most developers to use the resource or assets with static JSON definitions. However, there are `BlockFactory.addBlocks()` methods for both String and InputStream.  We didn't design for that use case, so the functionality isn't the most convenient, but you can look at `AbstractBlocklyActivity.reloadBlockdefinitions()` for an example of how to access and add to the BlockFactory, where all block definitions are stored.

**Comment by RoboErikG** [comment]
One other note, the code generators also make several assumptions about loading from the assets folder and there's no easy way to add block generators.

A somewhat painful option, if your dynamic blocks are simple enough we're currently working through adding mutators and functions to Android (they just landed in iOS). You could provide a generic block definition and a mutator that describes the dynamic blocks. You would want to prototype on web while we finish mutators on Android (and you'll need the web components to generate code anyway).

**Comment by levulinh** [comment]
@lijiansong Hi, I got the same problem. How did you solve it? I mean what did you delete and then rebuild the project? thank you

**Comment by lijiansong** [comment]
@levulinh Yes, after the first building, you will get the  blocklylib-core and blocklylib-vertical libraries, then delete them, and build the project again.

**Comment by levulinh** [comment]
@lijiansong so you deleted the library folders in project root folder or what?

**Comment by lijiansong** [comment]
@levulinh the library folders in project root

**Comment by levulinh** [comment]
@lijiansong Thank you. I've found out another way, I just add the release version of the libraries and set scope to compile, it works perfectly
