### ISSUE TITLE
inflating BasicFieldLabelView error 

### ISSUE THREAD

**Issue by huangxiaojingCN** [google/blockly-android#613]
android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class com.google.blockly.android.ui.fieldview.BasicFieldLabelView

**Comment by AnmAtAnm** [comment]
@huangxiaojingCN  Do you have any context for this error? Label views are very numerous in the Blockly standard blocks, and we have not seen any such issues.

**Comment by huangxiaojingCN** [comment]
@AnmAtAnm   
There is my error log 

![20170607205529](https://user-images.githubusercontent.com/20080084/26879522-ef0f1d28-4bc3-11e7-8778-094513139799.png)

**Comment by AnmAtAnm** [comment]
There isn't much detail in that log, but I'm guessing your application theme is not parented to `BlocklyVerticalTheme`.

From our getting started guide:

> 
> In the applications AppTheme, found in res/values/styles.xml, set the parent theme to BlocklyVerticalTheme.
> 
> ```
> <style name="AppTheme" parent="BlocklyVerticalTheme">
>     
>     ...
> </style>
> ```
> 
> This parent style configures several defaults for the blocks and fields. You can find more details in [the style's definition](https://github.com/google/blockly-android/blob/master/blocklylib-vertical/src/main/res/values/styles.xml).
