### ISSUE TITLE
Iterator variable inside list getter issue

### ISSUE THREAD

**Issue by contemplator1998** [google/blockly-android#630]
Hello,
The third line of generated code should be `test = list[item];`

![screenshot_2017-07-18-14-28-30](https://user-images.githubusercontent.com/5273056/28315244-55a7720c-6bc6-11e7-9df9-82530dc63de0.png)

**Comment by contemplator1998** [comment]
Hello, is this bug still unsolved? Thank you.

**Comment by AnmAtAnm** [comment]
Really sorry I totally missed this bug.  Fix in develop branch.
