### ISSUE TITLE
If block not generating code for else if and else statements

### ISSUE THREAD

**Issue by hfnovember** [google/blockly-android#666]

**Comment by AnmAtAnm** [comment]
Confirmed:
<img width="321" alt="screen shot 2017-10-02 at 5 37 49 pm" src="https://user-images.githubusercontent.com/9916202/31105373-94dfbb06-a798-11e7-8645-1b45ceed33ac.png">

    D/SimpleActivity: code:
      if (true) {
        window.alert('first');
      } else if (false) {
      } else {
      }
