### ISSUE TITLE
Numeric input and text input do not connect to existing blocks. Glitched block

### ISSUE THREAD

**Issue by mo-patel** [google/blockly-android#720]
When the numeric or text input blocks are connected to a set of existing blocks, the input does not connect properly. when dragging, the yellow indicator which highlights a possible connection does not appear either. Due to this issue, when the code generator is ran, the number input that does not connect always appears at the end of the code.

<img width="280" alt="screen shot 2018-03-11 at 10 35 40" src="https://user-images.githubusercontent.com/24302340/37252456-f353d692-2518-11e8-9d12-168c878b06f9.png">

<img width="148" alt="screen shot 2018-03-11 at 10 21 18" src="https://user-images.githubusercontent.com/24302340/37252421-ab76e67a-2518-11e8-9dda-a7d96371184c.png">

Also, When the block is dropped, the number input changes into a long number automatically which can be seen in the picture below

<img width="371" alt="screen shot 2018-03-11 at 10 20 39" src="https://user-images.githubusercontent.com/24302340/37252404-5be380c8-2518-11e8-9c9d-c99b81602b74.png">
. 

The scenario can be replicated by using AbstractBlocklyActivity with demo_workspace

**Comment by AnmAtAnm** [comment]
You attempting are connecting a number block or a text block to a boolean input. Since these connections are incompatible, this is the correct behavior.  Perhaps you want

```
if (numberValue != 0) { ... }
```

or

```
if (text.length == 0) { ... }
```
