### ISSUE TITLE
Variable Fields are Way Too Big

### ISSUE THREAD

**Issue by TheBrokenRail** [google/blockly-android#735]
Example on Blockly Demo App:

![screenshot_20180721-192546_blockly demo](https://user-images.githubusercontent.com/17478432/43040820-16df6480-8d1c-11e8-92ee-f8aa53dc2b5c.jpg)

**Comment by AnmAtAnm** [comment]
Something about how the spinner is measuring it preferred size when in the recycler view.  It does not happen once the the block is dropped onto the workspace.
