### ISSUE TITLE
Horizontal Toolbox Changes Height as You Scroll

### ISSUE THREAD

**Issue by TheBrokenRail** [google/blockly-android#739]
### Expected Behavior

_The toolbox is the height of the tallest block in the category or has a fixed height._

### Actual Behavior

_It changes height when you scroll and sometimes doesn't change back when you scroll back._

### Additional Information

_The GIF uses my app's code but it is the same in the "Blockly Flyouts" demo, it is just more noticeable in my setup._

### GIF Example

![untitled](https://user-images.githubusercontent.com/17478432/43371424-bf9b81be-935f-11e8-9214-11eafa99c0d5.gif)

**Comment by AnmAtAnm** [comment]
Thanks for the animation demonstrating the problem. I'm surprised the height does not bounce back when you scroll back.

Fixing this would require measuring all block group views to find the highest, and setting that as the height of the toolbox. However, the toolbox is really a `RecyclerView`, and the block group views are created on demand. Currently, there is no way to measure (or estimate) the height without creating the view.

Relatedly, there should probably also be a constraint to the max height of such a toolbox. Maybe not more than 60% of the work area?

**Comment by TheBrokenRail** [comment]
With out that many blocks in the toolbox would it hurt performance that much to disable recycling views on the toolbox and shouldn't there also be a minimum height of the toolbox?

**Comment by AnmAtAnm** [comment]
Replacing the recycler view for a small number of blocks (<20?) is a very reasonable approach. Having two paths does complicate testing.

And yes, the toolbox should have a minimum size (height if on the top or bottom, width otherwise).
