### ISSUE TITLE
Parsing Blockly generated xml in Android

### ISSUE THREAD

**Issue by praveenb** [google/blockly-android#749]
Generally i use Xstream parser for parsing XML. But XStream parser not working since this XML data has child tag same name as Parent tag. I found this [library ](https://github.com/Vilsol/Blockly2Java) which converts Blockly xml code to Java objects. But this library fails for Complex Blockly XML code. Please find the attached Blockly generated xml code. 
[blocky_issue.txt](https://github.com/google/blockly-android/files/2642839/blocky_issue.txt)

I don't see much help on Blockly parsing. 

Please let me know if there is any possible solution or any existing API library for parse Blockly generated XML code.

Thank you.

**Comment by AnmAtAnm** [comment]
For loading the workspace, use [BlocklyController.loadWorkspaceContents(..)](https://developers.google.com/blockly/reference/android/com/google/blockly/android/control/BlocklyController.html#loadWorkspaceContents(java.lang.String)). There are also simpler helper versions for specific locations: [BlocklyActivityHelper.loadWorkspaceFromAppDir(..)](https://developers.google.com/blockly/reference/android/com/google/blockly/android/BlocklyActivityHelper.html#loadWorkspaceFromAppDir(java.lang.String)), [BlocklyActivityHelper.loadWorkspaceFromAppDirSafely(..)](https://developers.google.com/blockly/reference/android/com/google/blockly/android/BlocklyActivityHelper.html#loadWorkspaceFromAppDirSafely(java.lang.String)).

Similar methods exist for the toolbox XML.

Under the hood, we use Android's built-in [XmlPullParser](https://developer.android.com/reference/org/xmlpull/v1/XmlPullParser). See [BlocklyXmlHelper.loadBlocksFromXml(..)](https://github.com/google/blockly-android/blob/develop/blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java#L430).
