### ISSUE TITLE
Crashed when swapped Math block into Logic Block

### ISSUE THREAD

**Issue by MarvinLu** [google/blockly-android#754]
**Drag out the block as shown below**

![_20190103_200712 1](https://user-images.githubusercontent.com/17266085/50637185-ee0dc600-0f93-11e9-8a4d-bbac528fa9b9.png)

when I dragging the math block into if....do group with swapping the  xx == xx block, app crashed.

that`s all.  need help @AnmAtAnm

**Comment by TheBrokenRail** [comment]
This is fixed with #755, this issue should be closed.
