### ISSUE TITLE
Use Vector Drawables Instead Of PNG Assets

### ISSUE THREAD

**Issue by TheBrokenRail** [google/blockly-android#763]

**Comment by AnmAtAnm** [comment]
Unfortunately, Android has very bad vector drawing performance for large area vectors. And in Blockly, this is compounded by our current view hierarchy. The original implementation did use vectors, but as block stack and a statement input block grew large (and not even excessively large), performance dropped to a crawl.

Even if this has changed in recent releases (and I have no hint it has), too many users and developers expect this library to work on older hardware, or low end hardware found in developing countries.  As such, I don't think this effort is appropriate right now.

Sorry for the late feedback.
