### ISSUE TITLE
Broken build after merging #757

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-android#768]
After merging #757, I'm getting the following error when building `develop`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleDebug' not found in project ':blocklydemo'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by TheBrokenRail** [comment]
That's because ```assembleDebug``` is not a task anymore, you have to do ```assembleFullDebug``` or ```assembleLiteDebug```.

**Comment by AnmAtAnm** [comment]
BlocklyDemo should be configured to automatically use the full version and should be buildable out of the box/repo using Android Studio to make it as easy as possible for developers to peek, hack, and explore.

Do you know what needs to change?

**Comment by TheBrokenRail** [comment]
It does automatically use the full version you just have to build it with ```assembleFullDebug```, ```assembleLiteDebug``` doesn't work on blocklydemo.
