### ISSUE TITLE
This is an issue. But I'm lost

### ISSUE THREAD

**Issue by skyestudiosDev** [google/blockly-android#780]
1. I basically want to build a blockly ide in Android that can generate Java codes in string format that I can run locally.

2. Customize the ide to my taste
Any help will be greatly appreciated. Thanks

**Comment by RoboErikG** [comment]
Start with the [Codelab](https://codelabs.developers.google.com/codelabs/blockly-web/index.html), then look at the [Android demo](https://github.com/google/blockly/tree/master/demos/mobile) as starting points. Generating Java is something that is possible but we don't provide direct support on as it requires additional work to get typing and compilation working.

And in the future, please ask questions on [the forums](https://groups.google.com/forum/#!forum/blockly). GitHub issues are for bugs and feature requests.
